name: Node.js CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-node:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version you want to use

      # Install dependencies if a package.json exists
      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm install
          fi

      # Run the Node.js file
      - name: Run the Node.js script
        run: node App.js

      # Echo a message
      - name: Echo message
        run: echo "Node.js script execution completed!"
